name: Deploy Django Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django_app/requirements.txt

      - name: Run Django migrations
        run: |
          cd django_app
          python manage.py migrate

      - name: Start Gunicorn server
        run: |
          cd django_app
          gunicorn hello.wsgi:application --bind 0.0.0.0:8000 --daemon
